AO3-3498 Display word count for drafts
otwcode/otwarchive pull request #3978
Opened 2021-02-23 06:37 UTC by britnesissom

# Pull Request Checklist

* [X] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [X] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [X] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [X] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [X] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-3498

## Purpose

When a draft or multiple drafts exist for an unposted work, display the word count as the sum of all drafts. For a posted work with drafts, display the word count as the sum of posted chapters only.

## Testing Instructions

Scenario 1
1. Create work with whichever fields you desire filled in
2. Click “preview” 
3. On the preview screen, click “save as draft”. 
4. go to your user’s drafts page and click “post draft”
5. word count will now have the correct number instead of being blank

Scenario 2
1. Create work with whichever fields you desire filled in
2. Click “preview” 
3. On the preview screen, click “save as draft”. 
4. Add a chapter to the work and save it as a draft too
5. word count will be the sum of these two chapters
6. Post the first chapter
7. word count will now be the count for the first chapter only

## Credit

*What name do you want us to use to credit your work in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)?*
agenderdanvers

*What pronouns do you prefer (she/her, he/him, zie/hir etc)?*
they/them

2021-03-07 09:24 UTC, sarken requested changes
Yay, thank you for working on this! There are some style comments, but the fix looks good.

Unfortunately, one of our coders noted that the changes to `post_first_chapter` mean that saving a previously-posted work with a draft first chapter won't cause the first chapter to be posted. That's ultimately the desired behavior, but we have two issues that make it undesirable at the present time: [AO3-4313](https://otwarchive.atlassian.net/browse/AO3-4313) & [AO3-5627](https://otwarchive.atlassian.net/browse/AO3-5627)

Because of that, we definitely don't want to merge this until pull request #3938 (for AO3-4313) is updated. Ideally, we'd also fix AO3-5627 in the same release, although I don't think that's quite as important as getting AO3-4313 fixed.

2021-03-07 19:48 UTC, tickinginstant commented on app/models/work.rb
> +      if !self.posted
If you want to simplify it further, I think you should also be able to compute the total word count with:
```
if self.posted
  chapters.posted.sum(:word_count)
else
  chapters.sum(:word_count)
end
```
That would also avoid Hound's complaint about `where(...).first`. (But that's a flaw in the existing code, so I don't think it's necessary to fix it.)

2021-03-10 21:41 UTC, britnesissom commented
@sarken @tickinginstant thanks for the coding suggestions! this is my first time using ruby/ror and cucumber so I did what I thought was best based on previous code ha. I will make these changes

2021-03-22 01:02 UTC, sarken reviewed
The code looks good! I just had a few more comments about code comment style and how the last two tests can be condensed.

One thing I did notice was that, even when I pulled both this **and** #3938 into a single branch, I got some odd behavior when deleting a work's only posted chapter as described in [AO3-5627](https://otwarchive.atlassian.net/browse/AO3-5627).

Regardless of whether I was logged in as an admin, a logged out user, or a logged in user who isn't a creator or invited co-creator on the work, I got the following error:

>Safari Can't Open the Page
>
>Too many redirects occurred trying to open "localhost:3000/works/1677723." This might occur if you open a page that is redirected to open another page which then is redirected to open the original page.

I don't think that needs to block us from merging this, since it's still arguably better than the current behavior (i.e. unexpectedly posting the chapter) I noted in AO3-5627's comments, but we'll definitely need to update the issue once this is merged.

2021-03-24 06:10 UTC, sarken reviewed
Three more tiny tweaks to the tests and this should be ready to go -- thank you!

2021-03-24 06:10 UTC, sarken commented on features/works/work_drafts.feature
> +      When I press "Preview"
This should probably be an "And", since it's still part of the initial set up.

2021-03-24 06:10 UTC, sarken commented on features/works/work_drafts.feature
> +      When I press "Preview"
This should also probably be an "And", since it's part of the initial set up of the draft (the "Given" steps).

2021-03-24 06:10 UTC, sarken commented on features/works/work_drafts.feature
> +      When I press "Post Chapter"
This should be "And" as well, since the step before it also begins with "When"

2021-03-24 13:54 UTC, britnesissom commented
@sarken sorry for all the updates. My tests will be better next time

2021-03-25 01:22 UTC, sarken approved these changes
Looks good, thank you! And no need to apologize -- it always takes a while to get used to the style on a new project. That's what code reviewers are here to help with!

2021-06-03 22:32 UTC, merged