Ao3 3828 link prompt fill to prompt
otwcode/otwarchive pull request #4048
Opened 2021-07-14 13:07 UTC by bellisk

# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [x] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-3828

## Purpose

When a work has been submitted to fulfill a prompt in a Prompt Meme collection, an automatically-inserted text in the work notes says so. This PR adds a link to the specific prompt to that text.

## Testing Instructions

1. Post a work that fulfills a prompt
2. Look at the automatically-inserted text in the work notes
3. Note that it says: "In response to a prompt by CREATOR in the COLLECTION_NAME collection."
4. Note that the word "prompt" is a link to the prompt in question.

## Credit

What name and pronouns should we use to credit you in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)?

katzenfabrik, they/them

2021-07-14 13:40 UTC, bellisk commented
The failing cucumber test passes locally (in Docker) and I really can't think of a way my change could affect admin caching of public skins.

2021-07-17 06:11 UTC, sarken requested changes
Thanks for this! However, I think it would be a good idea to extend the tests a bit and ensure that following the "prompt" link works, especially if the person following the link is logged out or logged in as a random user (i.e., not the challenge mod, work creator, or prompter).

2021-07-19 15:03 UTC, bellisk commented
@sarken Thanks, you're right. I'll add more tests.

2021-07-19 16:14 UTC, bellisk commented
Thanks @sarken - once I added those tests, I realised that logged-out users didn't have permission to see individual prompts, so I've fixed that too now. :)

2021-07-23 06:07 UTC, sarken requested changes
Yay for tests catching problems! I just have a couple of minor style suggestions about the tests, and then I think this will be ready to merge 👍

2021-07-23 06:07 UTC, sarken commented on features/prompt_memes_b/challenge_promptmeme_posting_fills.feature
> +  When I reveal works for "Battle 12"
Let's make all of these start with "And" and be indented under the initial "Given" step, since they're all sort of background/setup steps.

2021-07-23 06:07 UTC, sarken commented on features/prompt_memes_b/challenge_promptmeme_posting_fills.feature
> +    And I should see "Request by Anonymous"
When we're switching from checking the results (all of those "I should see" steps) to taking an action, we like to switch back to "When" -- and then back to "Then" for checking the results. So:

```
When I follow "prompt"
Then I should see "Request by Anonymous"
```

Lines 484 & 485, 491 & 492, and 498 & 499 also need this change.

2021-08-13 13:23 UTC, bellisk commented
@sarken Thanks for the codestyle tips! It's a lot clearer to me now how those cucumber tests are supposed to work. I've made the fixes you suggested. :)

2021-08-28 00:55 UTC, sarken approved these changes
This slipped through the cracks on me -- my apologies for that, and thanks for being patient! It looks good, so I'm going to stick it in our next release.

2021-08-28 00:58 UTC, merged