AO3-4728: Don't 500 on invalid subscribable
otwcode/otwarchive pull request #4150
Opened 2022-02-07 06:24 UTC by tlee911

## Issue

https://otwarchive.atlassian.net/browse/AO3-4728

## Purpose

Subscriptions page will no longer give 500 error if user has invalid subscribables (will show up as "DELETED" in the subscriptions list, and can be removed).

## Testing Instructions

I was unable to reproduce the problem without direct manipulation of the database, as all the ways listed in the Jira ticket for getting into this state seem to have been fixed previously (e.g. can no longer subscribe to a deleted work by keeping the work page open before the deletion).

I've added unit test in `models/subscription_spec.rb`, but haven't found a way to reliably reproduce without mucking around in the DB, and I'm not sure we want to be doing that in controller or cucumber tests.

For local testing, I created a subscription then modified it via SQL to point to a subscribable ID which does not exist, and verified the subscriptions page would still render, as well as allowing deletion of the invalid subscription.

2022-02-10 01:50 UTC, sarken requested changes

2022-02-10 01:50 UTC, sarken commented on app/views/subscriptions/index.html.erb
> +      <%= t(".deleted") %>
Can you indent this two spaces? And can we use `<%= subscription.name %>` here instead now that deleted subscriptions have a `name`? That would save Translation from having to translate the same thing twice.

2022-02-10 01:50 UTC, sarken commented on config/locales/models/en.yml
> +    deleted: "DELETED"
The placeholders in history use "Deleted work," so let's go with "Deleted item" here.

2022-02-10 01:52 UTC, sarken commented
>I've added unit test in models/subscription_spec.rb, but haven't found a way to reliably reproduce without mucking around in the DB, and I'm not sure we want to be doing that in controller or cucumber tests.

Oh, sorry, I forgot to mention -- this is fine! We muck around to create invalid items for controller or Cucumber tests all the time.

2022-02-11 00:33 UTC, tlee911 commented on app/views/subscriptions/index.html.erb
>        <% if params[:type].blank? && subscription.subscribable_type == "Work" %>
Can the subscription be nil? I meant to handle the case when the subscribable is nil (due to pointing to an entity that doesn't exist anymore).  If subscription is nil, wouldn't that mean there's no record to render?

2022-02-11 00:37 UTC, sarken commented on app/views/subscriptions/index.html.erb
>        <% if params[:type].blank? && subscription.subscribable_type == "Work" %>
Oh, right -- should be fine, then!

2022-02-12 01:10 UTC, sarken commented on config/locales/models/en.yml
> +    deleted: "Deleted item"
Just one more tiny nitpick -- can you add the missing newlines to the end of this file and locales/views/en.yml?

2022-02-15 02:05 UTC, sarken reviewed
The changes look good, but I think it's still missing tests to prove that the page will load and the subscription can be deleted. (If you'd like an example of how we set up invalid objects for Cucumber tests, [here's a step where we set up an invalid sign-up for gift exchanges](https://github.com/otwcode/otwarchive/blob/b10cff21682ae5a401a5f08488f6c448886a4070/features/step_definitions/challege_gift_exchange_steps.rb#L236-L241).)

2022-02-15 14:26 UTC, tlee911 commented
> The changes look good, but I think it's still missing tests to prove that the page will load and the subscription can be deleted. (If you'd like an example of how we set up invalid objects for Cucumber tests, [here's a step where we set up an invalid sign-up for gift exchanges](https://github.com/otwcode/otwarchive/blob/b10cff21682ae5a401a5f08488f6c448886a4070/features/step_definitions/challege_gift_exchange_steps.rb#L236-L241).)

Yup, I'm still meaning to do that.  Haven't had the time the last few days to sit down properly and work on it.  But the example is helpful.

2023-02-04 02:02 UTC, redsummernight commented on spec/controllers/subscriptions_controller_spec.rb
> +      let!(:sub_series) { create(:subscription, user: user, subscribable_type: "Series", subscribable_id: series.id) }
You should be able to use `create(:subscription, user: user, subscribable: series)`, etc.

2023-02-04 02:02 UTC, redsummernight commented on spec/controllers/subscriptions_controller_spec.rb
> +        expect(assigns(:subscriptions)).to satisfy { |subs| subs.size == 3 }
You can write `expect(assigns(:subscriptions)).to contain_exactly(sub_series, sub_work, sub_user)`.

2024-06-20 19:49 UTC, closed without merging