AO3-6342 Limit ability to list, create, update, and destroy admin banners.
otwcode/otwarchive pull request #4233
Opened 2022-05-14 20:14 UTC by tickinginstant

## Issue

https://otwarchive.atlassian.net/browse/AO3-6342

## Purpose

Add a new policy class for `AdminBanner`s, with all permissions set to allow only four admin roles: superadmin, support, communications, and board. Also modifies the controller to call `authorize` for each action, and hides the "Banner" link for other admins.

2022-05-15 05:42 UTC, sarken requested changes

2022-05-15 16:54 UTC, tickinginstant commented on app/policies/admin_banner_policy.rb
> +  def manage?
I realize it's the existing style, but it's always seemed redundant to me -- you have to call `policy(AdminBanner)` to get the policy in the first place, so the extra `banners` in the name is just unnecessary typing/reading. And the `can` is already implied by the fact that it's a policy.

Would it be okay if I removed this method and made all of the methods an alias of `index?` instead?

2022-05-16 02:42 UTC, sarken commented on app/policies/admin_banner_policy.rb
> +  def manage?
That'll work!

2022-05-16 19:29 UTC, sarken approved these changes

2022-05-16 19:29 UTC, merged