AO3-6243 Remove condition for comment form to be 'remote' to avoid CSRF token missing error
otwcode/otwarchive pull request #4322
Opened 2022-08-20 00:32 UTC by EchoEkhi

# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [x] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-6243

## Purpose

Fix editing a comment without JavaScript results in a session expired auth error.

## Testing Instructions

Follow instructions on JIRA.

## Credit

EchoEkhi (He/Him/{/([A-Z][a-z]*)/g})

2022-08-21 03:10 UTC, sarken commented
Thank you for the pull request! However, I'm going to temporarily close this, since it looks like you're currently over the limit of 5 open PRs. If you could pick another of your Awaiting Review PRs to close until you've had some PRs merged, we'd appreciate it.

2023-01-27 15:30 UTC, EchoEkhi commented
Could you please re-open this? I'm not allowed to re-open it apparently.

2023-06-01 03:09 UTC, sarken requested changes
Just one little syntax change -- the actual fix looks good!

2023-06-01 03:09 UTC, sarken commented on app/views/comments/_comment_form.html.erb
> +  <%= form_for value_for_comment_form(commentable, comment), :html => {:id => "comment_for_#{commentable.id}"} do |f| %>
Can you update the syntax here to `html: { id: "comment_for_#{commentable.id}" }`? Then this should be ready to go!

2023-06-10 06:24 UTC, sarken commented
I'm not sure _why_, since you didn't touch the locale files, but it looks like you'll need to run `bundle exec i18n-tasks normalize -l en` to make the tests pass on this.

2023-06-10 15:52 UTC, tickinginstant commented
I'm not convinced that this approach to fixing the issue is correct, since I believe this disables the remote form in all cases, even when editing a comment with JS enabled (which currently uses JS with a remote form). You might want to look into the `authenticity_token` argument on form helpers to try to resolve the CSRF error without otherwise changing the functionality.

If this approach is correct and the goal is to make it so that updating a comment never uses JS, even when JS is enabled, then you should probably also delete the code for updating a comment using JS, rather than leave the newly unused code lying around:
https://github.com/otwcode/otwarchive/blob/25150893db066858d83609cc52f36abf288d5071/app/controllers/comments_controller.rb#L376
https://github.com/otwcode/otwarchive/blob/25150893db066858d83609cc52f36abf288d5071/app/views/comments/update.js.erb#L1-L11
It would also be good to add some additional QA steps to cover the change in functionality.

2023-06-15 02:52 UTC, sarken commented
Thanks for catching that, ticking! I didn't notice the change in behavior at all when I pulled this and tried it out.

2023-06-15 02:56 UTC, sarken approved these changes

2023-06-19 03:24 UTC, merged