Ao3 6381 restrict admin access to spam
otwcode/otwarchive pull request #4336
Opened 2022-09-12 07:31 UTC by Cesium-Ice

# Pull Request Checklist

* [ ] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [ ] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [ ] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [ ] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [ ] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-6381

## Purpose

What does this PR do?
Restrict admin access to spam

## Testing Instructions

How can the Archive's QA team verify that this is working as you intended?
Refer to Jira

If you have a Jira account with access, please update or comment on the issue
with any new or missing testing instructions instead.

## References

Are there other relevant issues/pull requests/mailing list discussions?

## Credit

What name and pronouns should we use to credit you in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)?
Cesium-Ice,  she/her
If you have a Jira account, please include the same name in the "Full name"
field on your Jira profile, so we can assign you the issues you're working on.

*Please note that if you do not fill in this section, we will use your GitHub account name and
they/them pronouns.*

2022-09-12 08:04 UTC, Cesium-Ice commented
The failed tests involve gifts and orphaning, which I did not make any changes to, so I am unsure why they are failing.

2022-09-12 08:58 UTC, sarken commented
We have some [tests that fail intermittently](https://github.com/otwcode/otwarchive/wiki/Automated-Testing#Known_Test_Failures), so if you see a failure that's unrelated to your changes, there's a good chance it's not your fault. Someone will notice the red "x" and rerun the failed tests for you to make sure, though!

2022-09-13 20:41 UTC, sarken requested changes

2022-09-13 20:41 UTC, sarken commented on app/views/admin/_header.html.erb
> +
I think these changes were unintentional.

2022-09-13 20:41 UTC, sarken commented on app/views/admin/spam/index.html.erb
> +  <% end %>
I don't think you need this. Everyone who can access the index should be able to access the other pages as well.

2022-09-13 20:41 UTC, sarken commented on spec/controllers/admin/spam_controller_spec.rb
> +        it "marks moderated workd as reviewed, marks works as spam, hides the works, and redirects with notice" do
Could you fix the existing typo in this line? `workd` should be `works`.

2022-09-13 20:41 UTC, sarken commented on app/policies/spam_policy.rb
> +class SpamPolicy < ApplicationPolicy
I know these are called the spam pages, but maybe this should be the `ModeratedWorkPolicy` instead, so it's more obvious it's not related to spam comments. Or... should we use the `UserCreationPolicy` for this, considering it already controls the ability to mark works as spam? 

I think I'm going to solicit some additional opinions on this.

2022-09-14 20:51 UTC, Cesium-Ice commented
I accidentally made a commit to this pull request with the wrong account, is there a way to revert that or should I close this request and make a new one?

2022-09-14 21:04 UTC, sarken commented
You can try [reverting the merge commit](https://stackoverflow.com/a/7100005) , which I think is the erroneous one (it's hard to tell on mobile), but it might be easier to close and start fresh.

2022-09-14 21:21 UTC, Cesium-Ice commented on app/views/admin/_header.html.erb
> +
yup

2022-09-14 21:54 UTC, Cesium-Ice commented
Closing to open another PR

2022-09-14 21:54 UTC, closed without merging

2022-09-14 22:13 UTC, Cesium-Ice commented
New PR: https://github.com/otwcode/otwarchive/pull/4340