AO3-6473: Remove unused/unnecessary code from ApplicationController
otwcode/otwarchive pull request #4504
Opened 2023-04-29 00:12 UTC by gmjimenezc

# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [ ] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [x] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-6473
## Purpose

Remove unused code from ApplicationController

## Testing Instructions

No manual QA testing is needed for this

## References

Are there other relevant issues/pull requests/mailing list discussions?

## Credit

warlockmel (she/her)

2023-04-29 01:51 UTC, tickinginstant approved these changes
Looks good, thanks!

2023-08-13 03:47 UTC, sarken commented
It looks like we have some merge conflicts here -- would you be able to resolve them in the next couple days? If so, we can include this change in this release.

2023-12-01 08:29 UTC, sarken requested changes

2023-12-01 08:29 UTC, sarken commented on app/controllers/application_controller.rb
> -                      :set_redirects,
Looking at the test failures, I think we need to remove this in one other place now:

https://github.com/otwcode/otwarchive/blob/820914f3fd79c4f663bb820079740e6a8549ff4b/app/controllers/autocomplete_controller.rb#L6

2024-01-26 15:46 UTC, merged