AO3-6405 Task for removing multiple ratings on a work
otwcode/otwarchive pull request #4876
Opened 2024-07-18 02:22 UTC by ellieyhcheng

# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [x] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue
https://otwarchive.atlassian.net/browse/AO3-6405

## Purpose
Adds task for removing multiple ratings on a work, which was [a bug fixed about a year ago](https://otwarchive.atlassian.net/browse/AO3-6533) (sorry for the wait). 

## Testing Instructions
`docker compose run --rm test bundle exec rspec spec/lib/tasks/after_tasks.rake_spec.rb` passes. 

## References
N/A

## Credit
ellieyhcheng (she/her)

2024-07-29 19:09 UTC, brianjaustin requested changes
Thanks! A couple suggestions, plus the Rubocop ones. Please let me know if anything I said needs additional clarification!

2024-07-31 00:37 UTC, ellieyhcheng commented on lib/tasks/after_tasks.rake
> +    invalid_work_ids = []
Good idea, will do!

2024-07-31 00:40 UTC, ellieyhcheng commented on lib/tasks/after_tasks.rake
> +    invalid_works = Work.select { |work| work.ratings.size > 1 }
I'm not familiar with Elasticsearch, so I'm having some trouble integrating this with the spec tests. I can't quite figure out how to fill the indexer for the test (the query returns 0 works in the spec test). Is there a pointer to another spec test that does so?

2024-07-31 00:52 UTC, ellieyhcheng commented on lib/tasks/after_tasks.rake
> +    invalid_works = Work.select { |work| work.ratings.size > 1 }
Nevermind! The thing I tried after writing this comment worked (of course, it does). Will update the PR soon.

2024-08-04 00:26 UTC, brianjaustin approved these changes
Thanks!

2024-09-08 00:47 UTC, merged