AO3-6762: Restrict access to actions on TagsController
otwcode/otwarchive pull request #4917
Opened 2024-09-17 07:50 UTC by Cesium-Ice

# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [x] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-6762

## Purpose

What does this PR do?

## Testing Instructions

How can the Archive's QA team verify that this is working as you intended?

If you have a Jira account with access, please update or comment on the issue
with any new or missing testing instructions instead.

## References

Are there other relevant issues/pull requests/mailing list discussions?

## Credit

What name and pronouns should we use to credit you in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)?

Cesium-Ice, they/them

If you have a Jira account, please include the same name in the "Full name"
field on your Jira profile, so we can assign you the issues you're working on.

*Please note that if you do not fill in this section, we will use your GitHub account name and
they/them pronouns.*

2024-10-01 15:00 UTC, brianjaustin requested changes
Thank you! Just a few very small things, please let me know if you have any questions about them

2024-10-01 15:00 UTC, brianjaustin commented on app/policies/wrangling_policy.rb
> +  READ_ACCESS_ROLES  = (FULL_ACCESS_ROLES + %w[policy_and_abuse]).freeze
Please apply the Rubocop suggestion, just a quick space removal:
```suggestion
  READ_ACCESS_ROLES = (FULL_ACCESS_ROLES + %w[policy_and_abuse]).freeze
```
(for files that don't have other violations you can also do `rubocop -a <path/to/file>`, but that gets tricky with some old files that need loads of fixes)

2024-10-01 15:00 UTC, brianjaustin commented on spec/controllers/tags_controller_spec.rb
Small formatting nitpick:
```suggestion

      it_behaves_like "an action only fully authorized admins can access", authorized_roles: wrangling_full_access_roles
```

2024-10-01 15:00 UTC, brianjaustin commented on spec/controllers/tags_controller_spec.rb
> +  shared_examples "an action only fully authorized admins can access" do |authorized_roles:|
To me, "fully" implies the admin has write access. How about this?
```suggestion
  shared_examples "an action only authorized admins can access" do |authorized_roles:|
```

2024-10-01 16:57 UTC, brianjaustin approved these changes
Thank you!

2024-11-25 18:53 UTC, Bilka2 commented
This branch has a merge conflict, could you merge master and solve the conflict? We'd like to include this PR in a release soon.

2024-11-28 10:44 UTC, merged