AO3-6829 updates to the dmca policy
otwcode/otwarchive pull request #4953
Opened 2024-11-05 07:15 UTC by Nil-Cipher

# Pull Request Checklist

* [ ] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [ ] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [ ] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [ ] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [ ] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-XXXX (Please fill in issue number and remove this comment.)

## Purpose

What does this PR do?

## Testing Instructions

How can the Archive's QA team verify that this is working as you intended?

If you have a Jira account with access, please update or comment on the issue
with any new or missing testing instructions instead.

## References

Are there other relevant issues/pull requests/mailing list discussions?

## Credit

What name and pronouns should we use to credit you in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)?

If you have a Jira account, please include the same name in the "Full name"
field on your Jira profile, so we can assign you the issues you're working on.

*Please note that if you do not fill in this section, we will use your GitHub account name and
they/them pronouns.*

2024-11-05 07:20 UTC, sarken commented
Hi, Nil-Cipher!

Thank you for working on this! Someone will be along to review shortly after you move it out of Draft status. In the meantime, I've updated the Jira issue status to In Review, so no one will mistakenly create a duplicate pull request. 

If you'd like the ability to comment on, assign, and transition issues in the future, you're welcome to create a Jira account! You can just reply here with the account name and we'll set up the permissions for you. (It makes things a bit easier for us on the organizational side if the Full Name on your Jira account either closely matches the name you'd like us to credit in the release notes or includes it in parentheses, e.g. "Nickname (CREDIT NAME).")

Thanks again for contributing! If you have any questions, you can contact us at otw-coders@transformativeworks.org.

2024-11-05 07:23 UTC, Nil-Cipher commented
@sarken Do you have an auto-linter? I ran `erblint` and it caught some things, but I don't want to go and manually fix them.

2024-11-05 08:10 UTC, Nil-Cipher commented
Found an ERB linter in vscode. This is my first PR, so I didn't touch the i18 stuff. It seemed complicated with the large paragraphs, every `<p>` would need a new variable name and I'm not that creative. 
The test `other_a` is failing because I'm changing the html of the DMCA page.

2024-11-06 07:23 UTC, sarken requested changes
I've updated your Jira account permissions and assigned the issue to you! I noticed you haven't filled out the "Credit" section of the pull request template, so I just want to confirm: is Wanda the name you'd like us to credit in the release notes?

I've flagged a few small issues here that need to be corrected, and we'll also need you to update the test that's failing. It should look for other text that appears on this page but not the homepage, like "DMCA takedown notice."

Thanks again!

2024-11-07 05:12 UTC, Nil-Cipher commented on app/views/home/_dmca.html.erb
> +   <p>The Digital Millennium Copyright Act (DMCA) establishes the procedure the Organization for Transformative Works (OTW) must follow when users of our sites, including the Archive of Our Own (AO3)
Do you have a recommended linter?

2024-11-07 05:50 UTC, Nil-Cipher commented
> I've updated your Jira account permissions and assigned the issue to you! I noticed you haven't filled out the "Credit" section of the pull request template, so I just want to confirm: is Wanda the name you'd like us to credit in the release notes?
> 
> I've flagged a few small issues here that need to be corrected, and we'll also need you to update the test that's failing. It should look for other text that appears on this page but not the homepage, like "DMCA takedown notice."
> 
> Thanks again!

Yeah, nil-cipher (Wanda) is good as the credit name.

2024-11-07 06:00 UTC, Nil-Cipher commented
Woops, I tried to squash the commits and messed up the git history, will fix.

2024-11-07 06:07 UTC, Nil-Cipher commented
Should be all good now.

2024-11-08 00:15 UTC, sarken commented on app/views/home/_dmca.html.erb
> +   <p>The Digital Millennium Copyright Act (DMCA) establishes the procedure the Organization for Transformative Works (OTW) must follow when users of our sites, including the Archive of Our Own (AO3)
Oh, sorry, I thought you said you'd found it! As the [Coding Standards wiki page](https://github.com/otwcode/otwarchive/wiki/Coding-Standards#previewing-reviewdog-comments) mentions, we recommend erblint.

2024-11-08 00:26 UTC, sarken approved these changes
You don't have to change it back since it will be a moot point point when we internationalize the text, but just a heads up that it's a little better to leave the text on one line rather than splitting it across multiple lines to achieve a specific line length. When it's all on one line, fixing a typo/changing one word never requires changes to multiple lines.

Other than that, looks good -- thank you!

2024-11-19 05:55 UTC, lydia-theda commented on app/views/home/_dmca.html.erb
> +  <p><a href="/content#II.D.">Copyright infringement</a> and <a href="/content#II.E">plagiarism</a> are violations of
```suggestion
  <p><a href="/content#II.D">Copyright infringement</a> and <a href="/content#II.E">plagiarism</a> are violations of
```
Punctuation error in the provided HTML; the live anchor does not end in a period.

2024-11-19 07:05 UTC, sarken requested changes
Switching this over to Action Needed, given lydia's comment.

2024-11-22 21:08 UTC, sarken approved these changes

2024-11-22 21:09 UTC, merged

2024-11-22 22:11 UTC, lydia-theda commented on app/views/home/_dmca.html.erb
> +    Sections II.D. and II.E. of our <a href="/tos">Terms of Service</a>, respectively. For more information, please
For consistency with the TOS, please remove the trailing periods: 

Sections II.D and II.E of our Terms of Service

2024-11-22 22:19 UTC, lydia-theda commented on app/views/home/_dmca.html.erb
> +    Sections II.D. and II.E. of our <a href="/tos">Terms of Service</a>, respectively. For more information, please
requested edit: remove the periods after D and E 

  Sections II.D and II.E