AO3-5977 Hide "Approve All Unreviewed Comments" button from admins on works
otwcode/otwarchive pull request #4966
Opened 2024-11-21 22:07 UTC by WelpThatWorked

## Issue

https://otwarchive.atlassian.net/browse/AO3-5977

## Purpose

Hides the "Approve All Unreviewed Comments" button if an admin is viewing a work with comment moderation turned on.

## Credit

Jake Faulkner

2024-11-22 05:21 UTC, sarken requested changes
Hi, Jake, and thanks for the pull request! 

I've left a review comment, and while there's already [a test in features/admins/admin_post_news.feature](https://github.com/otwcode/otwarchive/blob/5ea268b75c40d40b7fc1f6094bfeaacaed712257/features/admins/admin_post_news.feature#L289-L295) that checks that the button _is_ visible on news posts, we'd appreciate it if you could add a test to [features/admins/admin_works.feature](https://github.com/otwcode/otwarchive/blob/5ea268b75c40d40b7fc1f6094bfeaacaed712257/features/admins/admin_works.feature) that ensures the button isn't visible on works.

I've assigned the Jira issue to you and set its status to In Review so no one will mistakenly create a duplicate pull request. I've also given your account permission to comment on, assign, and transition issues in the future.

Thanks again for contributing! If you have any questions, you can contact us at otw-coders@transformativeworks.org.

2024-11-22 05:21 UTC, sarken commented on app/controllers/comments_controller.rb
> +    @reviewable = (@commentable.is_a?(AdminPost) || current_user_owns?(@commentable))
I think a helper method might make more sense than a variable here. We have a bunch of methods for checking which comment-related buttons to display in the comments helper -- you might even be able to reuse this one: https://github.com/otwcode/otwarchive/blob/5ea268b75c40d40b7fc1f6094bfeaacaed712257/app/helpers/comments_helper.rb#L207-L211

2024-11-23 05:09 UTC, WelpThatWorked commented
Test added, threw in a check for the per-comment "Approve" button as well, since I don't see it anywhere else. 

Used the helper, and decided to let it hide the button on works with no unreviewed comments as well, since the button would do nothing in that case.

2024-11-26 07:09 UTC, sarken commented on app/views/comments/unreviewed.html.erb
> +<% if @comments[0] && can_review_comment?(@comments[0]) %>
I think `@comments.first` would be the more typical way to get the first comment in the array. 

That being said, if we have to deal with the possibilities of empty arrays here, it's probably tidier to define a new helper method that takes the commentable, e.g. 

```
def can_review_all_comments?(commentable)
  commentable.is_a?(AdminPost) || is_author_of?(commentable)
end
```

2024-11-26 07:55 UTC, WelpThatWorked commented on features/step_definitions/web_steps.rb
> +
Thanks, not sure how I overlooked these.

2024-11-27 06:46 UTC, sarken approved these changes
Thank you!

2025-01-22 17:29 UTC, merged